// File: utils/currencyData.js
// Replace the entire contents of your file with this.

export const CURRENCY_DATA = {
  AED: { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ', flag: '🇦🇪' },
  AFN: { code: 'AFN', name: 'Afghan Afghani', symbol: '؋', flag: '🇦🇫' },
  ALL: { code: 'ALL', name: 'Albanian Lek', symbol: 'L', flag: '🇦🇱' },
  AMD: { code: 'AMD', name: 'Armenian Dram', symbol: '֏', flag: '🇦🇲' },
  ANG: { code: 'ANG', name: 'Netherlands Antillean Guilder', symbol: 'ƒ', flag: '🇨🇼' },
  AOA: { code: 'AOA', name: 'Angolan Kwanza', symbol: 'Kz', flag: '🇦🇴' },
  ARS: { code: 'ARS', name: 'Argentine Peso', symbol: '$', flag: '🇦🇷' },
  AUD: { code: 'AUD', name: 'Australian Dollar', symbol: '$', flag: '🇦🇺' },
  AWG: { code: 'AWG', name: 'Aruban Florin', symbol: 'ƒ', flag: '🇦🇼' },
  AZN: { code: 'AZN', name: 'Azerbaijani Manat', symbol: '₼', flag: '🇦🇿' },
  BAM: { code: 'BAM', name: 'Bosnia-Herzegovina Convertible Mark', symbol: 'KM', flag: '🇧🇦' },
  BBD: { code: 'BBD', name: 'Barbadian Dollar', symbol: '$', flag: '🇧🇧' },
  BDT: { code: 'BDT', name: 'Bangladeshi Taka', symbol: '৳', flag: '🇧🇩' },
  BGN: { code: 'BGN', name: 'Bulgarian Lev', symbol: 'лв', flag: '🇧🇬' },
  BHD: { code: 'BHD', name: 'Bahraini Dinar', symbol: '.د.ب', flag: '🇧🇭' },
  BIF: { code: 'BIF', name: 'Burundian Franc', symbol: 'FBu', flag: '🇧🇮' },
  BMD: { code: 'BMD', name: 'Bermudan Dollar', symbol: '$', flag: '🇧🇲' },
  BND: { code: 'BND', name: 'Brunei Dollar', symbol: '$', flag: '🇧🇳' },
  BOB: { code: 'BOB', name: 'Bolivian Boliviano', symbol: 'Bs.', flag: '🇧🇴' },
  BRL: { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', flag: '🇧🇷' },
  BSD: { code: 'BSD', name: 'Bahamian Dollar', symbol: '$', flag: '🇧🇸' },
  BTN: { code: 'BTN', name: 'Bhutanese Ngultrum', symbol: 'Nu.', flag: '🇧🇹' },
  BWP: { code: 'BWP', name: 'Botswanan Pula', symbol: 'P', flag: '🇧🇼' },
  BYN: { code: 'BYN', name: 'Belarusian Ruble', symbol: 'Br', flag: '🇧🇾' },
  BZD: { code: 'BZD', name: 'Belize Dollar', symbol: 'BZ$', flag: '🇧🇿' },
  CAD: { code: 'CAD', name: 'Canadian Dollar', symbol: '$', flag: '🇨🇦' },
  CDF: { code: 'CDF', name: 'Congolese Franc', symbol: 'FC', flag: '🇨🇩' },
  CHF: { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', flag: '🇨🇭' },
  CLP: { code: 'CLP', name: 'Chilean Peso', symbol: '$', flag: '🇨🇱' },
  CNY: { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', flag: '🇨🇳' },
  COP: { code: 'COP', name: 'Colombian Peso', symbol: '$', flag: '🇨🇴' },
  CRC: { code: 'CRC', name: 'Costa Rican Colón', symbol: '₡', flag: '🇨🇷' },
  CUP: { code: 'CUP', name: 'Cuban Peso', symbol: '$', flag: '🇨🇺' },
  CVE: { code: 'CVE', name: 'Cape Verdean Escudo', symbol: '$', flag: '🇨🇻' },
  CZK: { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', flag: '🇨🇿' },
  DJF: { code: 'DJF', name: 'Djiboutian Franc', symbol: 'Fdj', flag: '🇩🇯' },
  DKK: { code: 'DKK', name: 'Danish Krone', symbol: 'kr', flag: '🇩🇰' },
  DOP: { code: 'DOP', name: 'Dominican Peso', symbol: 'RD$', flag: '🇩🇴' },
  DZD: { code: 'DZD', name: 'Algerian Dinar', symbol: 'د.ج', flag: '🇩🇿' },
  EGP: { code: 'EGP', name: 'Egyptian Pound', symbol: '£', flag: '🇪🇬' },
  ERN: { code: 'ERN', name: 'Eritrean Nakfa', symbol: 'Nfk', flag: '🇪🇷' },
  ETB: { code: 'ETB', name: 'Ethiopian Birr', symbol: 'Br', flag: '🇪🇹' },
  EUR: { code: 'EUR', name: 'Euro', symbol: '€', flag: '🇪🇺' },
  FJD: { code: 'FJD', name: 'Fijian Dollar', symbol: '$', flag: '🇫🇯' },
  FKP: { code: 'FKP', name: 'Falkland Islands Pound', symbol: '£', flag: '🇫🇰' },
  FOK: { code: 'FOK', name: 'Faroese Króna', symbol: 'kr', flag: '🇫🇴' },
  GBP: { code: 'GBP', name: 'British Pound Sterling', symbol: '£', flag: '🇬🇧' },
  GEL: { code: 'GEL', name: 'Georgian Lari', symbol: '₾', flag: '🇬🇪' },
  GGP: { code: 'GGP', name: 'Guernsey Pound', symbol: '£', flag: '🇬🇬' },
  GHS: { code: 'GHS', name: 'Ghanaian Cedi', symbol: '₵', flag: '🇬🇭' },
  GIP: { code: 'GIP', name: 'Gibraltar Pound', symbol: '£', flag: '🇬🇮' },
  GMD: { code: 'GMD', name: 'Gambian Dalasi', symbol: 'D', flag: '🇬🇲' },
  GNF: { code: 'GNF', name: 'Guinean Franc', symbol: 'FG', flag: '🇬🇳' },
  GTQ: { code: 'GTQ', name: 'Guatemalan Quetzal', symbol: 'Q', flag: '🇬🇹' },
  GYD: { code: 'GYD', name: 'Guyanaese Dollar', symbol: '$', flag: '🇬🇾' },
  HKD: { code: 'HKD', name: 'Hong Kong Dollar', symbol: '$', flag: '🇭🇰' },
  HNL: { code: 'HNL', name: 'Honduran Lempira', symbol: 'L', flag: '🇭🇳' },
  HRK: { code: 'HRK', name: 'Croatian Kuna', symbol: 'kn', flag: '🇭🇷' },
  HTG: { code: 'HTG', name: 'Haitian Gourde', symbol: 'G', flag: '🇭🇹' },
  HUF: { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', flag: '🇭🇺' },
  IDR: { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', flag: '🇮🇩' },
  ILS: { code: 'ILS', name: 'Israeli New Shekel', symbol: '₪', flag: '🇮🇱' },
  IMP: { code: 'IMP', name: 'Isle of Man Pound', symbol: '£', flag: '🇮🇲' },
  INR: { code: 'INR', name: 'Indian Rupee', symbol: '₹', flag: '🇮🇳' },
  IQD: { code: 'IQD', name: 'Iraqi Dinar', symbol: 'ع.د', flag: '🇮🇶' },
  IRR: { code: 'IRR', name: 'Iranian Rial', symbol: '﷼', flag: '🇮🇷' },
  ISK: { code: 'ISK', name: 'Icelandic Króna', symbol: 'kr', flag: '🇮🇸' },
  JEP: { code: 'JEP', name: 'Jersey Pound', symbol: '£', flag: '🇯🇪' },
  JMD: { code: 'JMD', name: 'Jamaican Dollar', symbol: 'J$', flag: '🇯🇲' },
  JOD: { code: 'JOD', name: 'Jordanian Dinar', symbol: 'JD', flag: '🇯🇴' },
  JPY: { code: 'JPY', name: 'Japanese Yen', symbol: '¥', flag: '🇯🇵' },
  KES: { code: 'KES', name: 'Kenyan Shilling', symbol: 'KSh', flag: '🇰🇪' },
  KGS: { code: 'KGS', name: 'Kyrgystani Som', symbol: 'с', flag: '🇰🇬' },
  KHR: { code: 'KHR', name: 'Cambodian Riel', symbol: '៛', flag: '🇰🇭' },
  KID: { code: 'KID', name: 'Kiribati Dollar', symbol: '$', flag: '🇰🇮' },
  KMF: { code: 'KMF', name: 'Comorian Franc', symbol: 'CF', flag: '🇰🇲' },
  KRW: { code: 'KRW', name: 'South Korean Won', symbol: '₩', flag: '🇰🇷' },
  KWD: { code: 'KWD', name: 'Kuwaiti Dinar', symbol: 'د.ك', flag: '🇰🇼' },
  KYD: { code: 'KYD', name: 'Cayman Islands Dollar', symbol: '$', flag: '🇰🇾' },
  KZT: { code: 'KZT', name: 'Kazakhstani Tenge', symbol: '₸', flag: '🇰🇿' },
  LAK: { code: 'LAK', name: 'Laotian Kip', symbol: '₭', flag: '🇱🇦' },
  LBP: { code: 'LBP', name: 'Lebanese Pound', symbol: 'ل.ل', flag: '🇱🇧' },
  LKR: { code: 'LKR', name: 'Sri Lankan Rupee', symbol: '₨', flag: '🇱🇰' },
  LRD: { code: 'LRD', name: 'Liberian Dollar', symbol: '$', flag: '🇱🇷' },
  LSL: { code: 'LSL', name: 'Lesotho Loti', symbol: 'L', flag: '🇱🇸' },
  LYD: { code: 'LYD', name: 'Libyan Dinar', symbol: 'ل.د', flag: '🇱🇾' },
  MAD: { code: 'MAD', name: 'Moroccan Dirham', symbol: 'د.م.', flag: '🇲🇦' },
  MDL: { code: 'MDL', name: 'Moldovan Leu', symbol: 'L', flag: '🇲🇩' },
  MGA: { code: 'MGA', name: 'Malagasy Ariary', symbol: 'Ar', flag: '🇲🇬' },
  MKD: { code: 'MKD', name: 'Macedonian Denar', symbol: 'ден', flag: '🇲🇰' },
  MMK: { code: 'MMK', name: 'Myanmar Kyat', symbol: 'K', flag: '🇲🇲' },
  MNT: { code: 'MNT', name: 'Mongolian Tugrik', symbol: '₮', flag: '🇲🇳' },
  MOP: { code: 'MOP', name: 'Macanese Pataca', symbol: 'MOP$', flag: '🇲🇴' },
  MRU: { code: 'MRU', name: 'Mauritanian Ouguiya', symbol: 'UM', flag: '🇲🇷' },
  MUR: { code: 'MUR', name: 'Mauritian Rupee', symbol: '₨', flag: '🇲🇺' },
  MVR: { code: 'MVR', name: 'Maldivian Rufiyaa', symbol: 'Rf', flag: '🇲🇻' },
  MWK: { code: 'MWK', name: 'Malawian Kwacha', symbol: 'MK', flag: '🇲🇼' },
  MXN: { code: 'MXN', name: 'Mexican Peso', symbol: '$', flag: '🇲🇽' },
  MYR: { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', flag: '🇲🇾' },
  MZN: { code: 'MZN', name: 'Mozambican Metical', symbol: 'MT', flag: '🇲🇿' },
  NAD: { code: 'NAD', name: 'Namibian Dollar', symbol: '$', flag: '🇳🇦' },
  NGN: { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', flag: '🇳🇬' },
  NIO: { code: 'NIO', name: 'Nicaraguan Córdoba', symbol: 'C$', flag: '🇳🇮' },
  NOK: { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', flag: '🇳🇴' },
  NPR: { code: 'NPR', name: 'Nepalese Rupee', symbol: '₨', flag: '🇳🇵' },
  NZD: { code: 'NZD', name: 'New Zealand Dollar', symbol: '$', flag: '🇳🇿' },
  OMR: { code: 'OMR', name: 'Omani Rial', symbol: 'ر.ع.', flag: '🇴🇲' },
  PAB: { code: 'PAB', name: 'Panamanian Balboa', symbol: 'B/.', flag: '🇵🇦' },
  PEN: { code: 'PEN', name: 'Peruvian Nuevo Sol', symbol: 'S/.', flag: '🇵🇪' },
  PGK: { code: 'PGK', name: 'Papua New Guinean Kina', symbol: 'K', flag: '🇵🇬' },
  PHP: { code: 'PHP', name: 'Philippine Peso', symbol: '₱', flag: '🇵🇭' },
  PKR: { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨', flag: '🇵🇰' },
  PLN: { code: 'PLN', name: 'Polish Zloty', symbol: 'zł', flag: '🇵🇱' },
  PYG: { code: 'PYG', name: 'Paraguayan Guarani', symbol: '₲', flag: '🇵🇾' },
  QAR: { code: 'QAR', name: 'Qatari Rial', symbol: 'ر.ق', flag: '🇶🇦' },
  RON: { code: 'RON', name: 'Romanian Leu', symbol: 'lei', flag: '🇷🇴' },
  RSD: { code: 'RSD', name: 'Serbian Dinar', symbol: 'дин.', flag: '🇷🇸' },
  RUB: { code: 'RUB', name: 'Russian Ruble', symbol: '₽', flag: '🇷🇺' },
  RWF: { code: 'RWF', name: 'Rwandan Franc', symbol: 'FRw', flag: '🇷🇼' },
  SAR: { code: 'SAR', name: 'Saudi Riyal', symbol: 'ر.س', flag: '🇸🇦' },
  SBD: { code: 'SBD', name: 'Solomon Islands Dollar', symbol: '$', flag: '🇸🇧' },
  SCR: { code: 'SCR', name: 'Seychellois Rupee', symbol: '₨', flag: '🇸🇨' },
  SDG: { code: 'SDG', name: 'Sudanese Pound', symbol: 'ج.س.', flag: '🇸🇩' },
  SEK: { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', flag: '🇸🇪' },
  SGD: { code: 'SGD', name: 'Singapore Dollar', symbol: '$', flag: '🇸🇬' },
  SHP: { code: 'SHP', name: 'Saint Helena Pound', symbol: '£', flag: '🇸🇭' },
  SLE: { code: 'SLE', name: 'Sierra Leonean Leone', symbol: 'Le', flag: '🇸🇱' },
  SOS: { code: 'SOS', name: 'Somali Shilling', symbol: 'S', flag: '🇸🇴' },
  SRD: { code: 'SRD', name: 'Surinamese Dollar', symbol: '$', flag: '🇸🇷' },
  SSP: { code: 'SSP', name: 'South Sudanese Pound', symbol: '£', flag: '🇸🇸' },
  STN: { code: 'STN', name: 'São Tomé & Príncipe Dobra', symbol: 'Db', flag: '🇸🇹' },
  SYP: { code: 'SYP', name: 'Syrian Pound', symbol: '£', flag: '🇸🇾' },
  SZL: { code: 'SZL', name: 'Swazi Lilangeni', symbol: 'L', flag: '🇸🇿' },
  THB: { code: 'THB', name: 'Thai Baht', symbol: '฿', flag: '🇹🇭' },
  TJS: { code: 'TJS', name: 'Tajikistani Somoni', symbol: 'ЅМ', flag: '🇹🇯' },
  TMT: { code: 'TMT', name: 'Turkmenistani Manat', symbol: 'm', flag: '🇹🇲' },
  TND: { code: 'TND', name: 'Tunisian Dinar', symbol: 'د.ت', flag: '🇹🇳' },
  TOP: { code: 'TOP', name: 'Tongan Paʻanga', symbol: 'T$', flag: '🇹🇴' },
  TRY: { code: 'TRY', name: 'Turkish Lira', symbol: '₺', flag: '🇹🇷' },
  TTD: { code: 'TTD', name: 'Trinidad & Tobago Dollar', symbol: 'TT$', flag: '🇹🇹' },
  TVD: { code: 'TVD', name: 'Tuvaluan Dollar', symbol: '$', flag: '🇹🇻' },
  TWD: { code: 'TWD', name: 'New Taiwan Dollar', symbol: 'NT$', flag: '🇹🇼' },
  TZS: { code: 'TZS', name: 'Tanzanian Shilling', symbol: 'TSh', flag: '🇹🇿' },
  UAH: { code: 'UAH', name: 'Ukrainian Hryvnia', symbol: '₴', flag: '🇺🇦' },
  UGX: { code: 'UGX', name: 'Ugandan Shilling', symbol: 'USh', flag: '🇺🇬' },
  USD: { code: 'USD', name: 'United States Dollar', symbol: '$', flag: '🇺🇸' },
  UYU: { code: 'UYU', name: 'Uruguayan Peso', symbol: '$U', flag: '🇺🇾' },
  UZS: { code: 'UZS', name: 'Uzbekistan Som', symbol: 'soʻm', flag: '🇺🇿' },
  VES: { code: 'VES', name: 'Venezuelan Bolívar', symbol: 'Bs.', flag: '🇻🇪' },
  VND: { code: 'VND', name: 'Vietnamese Dong', symbol: '₫', flag: '🇻🇳' },
  VUV: { code: 'VUV', name: 'Vanuatu Vatu', symbol: 'VT', flag: '🇻🇺' },
  WST: { code: 'WST', name: 'Samoan Tala', symbol: 'T', flag: '🇼🇸' },
  XAF: { code: 'XAF', name: 'CFA Franc BEAC', symbol: 'FCFA', flag: '🇨🇫' },
  XCD: { code: 'XCD', name: 'East Caribbean Dollar', symbol: '$', flag: '🇦🇬' },
  XDR: { code: 'XDR', name: 'Special Drawing Rights', symbol: 'SDR', flag: '🏳️' },
  XOF: { code: 'XOF', name: 'CFA Franc BCEAO', symbol: 'CFA', flag: '🇸🇳' },
  XPF: { code: 'XPF', name: 'CFP Franc', symbol: '₣', flag: '🇵🇫' },
  YER: { code: 'YER', name: 'Yemeni Rial', symbol: '﷼', flag: '🇾🇪' },
  ZAR: { code: 'ZAR', name: 'South African Rand', symbol: 'R', flag: '🇿🇦' },
  ZMW: { code: 'ZMW', name: 'Zambian Kwacha', symbol: 'ZK', flag: '🇿🇲' },
  ZWL: { code: 'ZWL', name: 'Zimbabwean Dollar', symbol: '$', flag: '🇿🇼' },
};